// src/app/(authenticated)/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Navbar from "@/components/Navbar"
import SessionProvider from "@/components/SessionProvider"
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { UserRole } from "@prisma/client"

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nicole Germain ERP",
  description: "Generated by create next app",
};

export default async function AuthenticatedLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)
  
  let activeFeatures: string[] = []

  // On vérifie que le rôle existe bien dans l'énumération Prisma
  if (session?.user?.role && Object.values(UserRole).includes(session.user.role as UserRole)) {
    const roleEnum = session.user.role as UserRole

    const permissions = await prisma.rolePermission.findMany({
      where: {
        role: roleEnum, // 🔒 Utilise le rôle parfaitement nettoyé et typé
        canAccess: true
      }
    })
    
    activeFeatures = permissions.map(p => p.feature)
  }

  // Pour débugger facilement, affiche ce que ton serveur trouve dans ton terminal :
  console.log(`🔑 Rôle connecté : ${session?.user?.role} | Droits BDD :`, activeFeatures)

  return (
    <SessionProvider>
      <div className="min-h-screen bg-slate-50">
        <Navbar userPermissions={activeFeatures} />
        <main className="w-full max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {children}
        </main>
      </div>
    </SessionProvider>
  )
}